### ISSUE TITLE
Why Pivy rather than VNCoreNLP?

### ISSUE THREAD

**Issue by bui-thanh-lam** [vovanphuc/SimeCSE_Vietnamese#1]
Chào anh,

Em có thắc mắc rằng PhoBERT dùng VNCoreNLP cho bước segment. Vậy tại sao anh lại dùng Pivy?
Do quá trình pretrain của anh dùng Pivy thấy tốt hơn, hay giữa 2 bộ segment này không khác biệt nhau nhiều, trong khi đó dùng pivy tiện hơn (không cần Java).
Qua kinh nghiệm sử dụng, cá nhân em thấy VNCoreNLP cho performance tốt hơn (nếu data là tiếng Việt chuẩn).

**Comment by vovanphuc** [comment]
VNCoreNLP cho performance tốt hơn, nhưng khi training SimCSE mình chọn pivy vì dễ viết data loader hơn, và mình thấy sự chênh lệch không đáng kể. Hơn nữa, mình đã training SimCSE ở 1 tập khá lớn sử dụng pivy nên inference bạn sử dụng pyvi hoàn toàn không có vấn đề gì.
